# Generated by Django 4.0 on 2021-12-19 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=6)),
                ('executed_qty', models.PositiveIntegerField()),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
